title: World's Biggest SaaS Directory List
description: A free, curated A to Z list of 320+ SaaS directories, AI tool directories, and software review sites for backlinks, launches, and reviews. Updated regularly.
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://andrew-whitefield.github.io"
baseurl: "/saas-directories-list"

google_site_verification: "y_L4KBTzShf0VXQ3m6BUyApHe0Ulks2nypjO_X9AW9I"

author: Andrew Whitefield
